server.port: 8104
spring.application.name: session-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
  instance:
    preferIpAddress: true

spring:
  config:
    import: "optional:configserver:"